### ISSUE TITLE
Rename system modes nodes to match ontology

### ISSUE THREAD

**Issue by Rezenders** [kas-lab/pipeline_inspection#53]
Something like:

```
f_generate_search_path:
  ros__parameters:
    type: node
    modes:
      fd_spiral_low:
        ros__parameters:
          spiral_width: 0.5
      fd_spiral_medium:
        ros__parameters:
          spiral_width: 1.0
      fd_spiral_high:
        ros__parameters:
          spiral_width: 2.0
```
